"use client";

import { useEffect, useRef } from "react";

/**
 * Disclaimer modal triggered from the drawer footer. Uses the native
 * <dialog> element + showModal() so we get focus-trap and ESC-to-close
 * for free with no library. Backdrop clicks close too — the trick is
 * checking `e.target === dialogRef.current`, which only matches when
 * the click landed on the dialog's own (transparent) padding area
 * rather than on the inner content card that has its own background.
 */
export function DisclaimerDialog() {
  const dialogRef = useRef<HTMLDialogElement>(null);

  // Lock body scroll while the dialog is open so the dashboard
  // doesn't jiggle behind it on iOS / mobile.
  useEffect(() => {
    const dlg = dialogRef.current;
    if (!dlg) return;
    const handleClose = () => {
      document.body.style.overflow = "";
    };
    dlg.addEventListener("close", handleClose);
    return () => dlg.removeEventListener("close", handleClose);
  }, []);

  function open() {
    if (!dialogRef.current) return;
    document.body.style.overflow = "hidden";
    dialogRef.current.showModal();
  }
  function close() {
    dialogRef.current?.close();
  }

  return (
    <>
      <button type="button" className="footer-link-button" onClick={open}>
        DISCLAIMER
      </button>
      <dialog
        ref={dialogRef}
        className="disclaimer-dialog"
        onClick={(e) => {
          // Backdrop click — only close when the click hits the
          // dialog itself, not the inner content panel.
          if (e.target === dialogRef.current) close();
        }}
      >
        <article className="disclaimer-panel">
          <header className="disclaimer-header">
            <h2 className="disclaimer-title">DISCLAIMER</h2>
            <button
              type="button"
              className="disclaimer-close"
              onClick={close}
              aria-label="Close disclaimer"
            >
              ×
            </button>
          </header>
          <div className="disclaimer-body">
            <p>
              <strong>Look — this site is for fun.</strong>
            </p>
            <p>
              ISKBets is a side project tracking a curated list of stocks for a
              small group of friends. Prices come from public APIs (Finnhub free
              tier for US tickers, Avanza&apos;s unofficial JSON for Stockholm)
              and may be delayed, incorrect, or completely missing. The
              commentary is generated by Claude — it&apos;s entertainment, not
              analysis.
            </p>
            <p>
              <strong>
                Nothing on this site is financial, investment, tax, or legal
                advice.
              </strong>{" "}
              The author is not a registered financial advisor. The friends
              named here don&apos;t endorse anything. The &ldquo;ratings&rdquo;
              and &ldquo;moods&rdquo; are jokes.
            </p>
            <p>
              Past performance does not predict future results. Stocks go down
              as well as up. Do your own research. Talk to an actual advisor
              before making real investment decisions.
            </p>
            <p>
              By using this site you accept that any decisions you make based on
              it are your own responsibility. The author is not liable for any
              losses, missed gains, ulcers, or hurt feelings.
            </p>
            <p className="disclaimer-signoff">Now go touch grass. 🦍</p>
          </div>
        </article>
      </dialog>
    </>
  );
}
