import type { StockAnalysis, StockPrice, StoredData } from "./types";

const STOCKS: StockPrice[] = [
  // ============== US — WSB darlings ==============
  {
    ticker: "NVDA",
    name: "Nvidia",
    currency: "USD",
    regularMarketPrice: 142.85,
    regularMarketChange: 9.07,
    regularMarketChangePercent: 6.8,
    regularMarketVolume: 235_000_000,
    averageDailyVolume3Month: 180_000_000,
    fiftyTwoWeekHigh: 148.0,
    fiftyTwoWeekLow: 84.5,
    marketState: "REGULAR",
  },
  {
    ticker: "TSLA",
    name: "Tesla",
    currency: "USD",
    regularMarketPrice: 428.6,
    regularMarketChange: 19.61,
    regularMarketChangePercent: 4.8,
    regularMarketVolume: 92_000_000,
    averageDailyVolume3Month: 78_000_000,
    fiftyTwoWeekHigh: 488.5,
    fiftyTwoWeekLow: 178.0,
    marketState: "REGULAR",
  },
  {
    ticker: "GME",
    name: "GameStop",
    currency: "USD",
    regularMarketPrice: 22.85,
    regularMarketChange: -2.32,
    regularMarketChangePercent: -9.2,
    regularMarketVolume: 18_500_000,
    averageDailyVolume3Month: 9_400_000,
    fiftyTwoWeekHigh: 64.83,
    fiftyTwoWeekLow: 9.95,
    marketState: "REGULAR",
  },
  {
    ticker: "PLTR",
    name: "Palantir",
    currency: "USD",
    regularMarketPrice: 72.4,
    regularMarketChange: 2.18,
    regularMarketChangePercent: 3.1,
    regularMarketVolume: 45_000_000,
    averageDailyVolume3Month: 62_000_000,
    fiftyTwoWeekHigh: 84.0,
    fiftyTwoWeekLow: 21.0,
    marketState: "REGULAR",
  },
  {
    ticker: "AMD",
    name: "AMD",
    currency: "USD",
    regularMarketPrice: 132.6,
    regularMarketChange: 2.34,
    regularMarketChangePercent: 1.8,
    regularMarketVolume: 38_000_000,
    averageDailyVolume3Month: 45_000_000,
    fiftyTwoWeekHigh: 187.0,
    fiftyTwoWeekLow: 116.0,
    marketState: "PRE",
  },
  {
    ticker: "COIN",
    name: "Coinbase",
    currency: "USD",
    regularMarketPrice: 278.4,
    regularMarketChange: -4.24,
    regularMarketChangePercent: -1.5,
    regularMarketVolume: 11_200_000,
    averageDailyVolume3Month: 9_800_000,
    fiftyTwoWeekHigh: 343.0,
    fiftyTwoWeekLow: 142.5,
    marketState: "REGULAR",
  },
  {
    ticker: "MSTR",
    name: "MicroStrategy",
    currency: "USD",
    regularMarketPrice: 382.1,
    regularMarketChange: 4.53,
    regularMarketChangePercent: 1.2,
    regularMarketVolume: 14_500_000,
    averageDailyVolume3Month: 18_200_000,
    fiftyTwoWeekHigh: 543.0,
    fiftyTwoWeekLow: 184.0,
    marketState: "REGULAR",
  },
  // ============== Sweden — ISK staples ==============
  {
    ticker: "INVE-B.ST",
    name: "Investor B",
    currency: "SEK",
    regularMarketPrice: 285.4,
    regularMarketChange: 3.94,
    regularMarketChangePercent: 1.4,
    regularMarketVolume: 1_240_000,
    averageDailyVolume3Month: 1_800_000,
    fiftyTwoWeekHigh: 302.0,
    fiftyTwoWeekLow: 240.5,
    marketState: "REGULAR",
  },
  {
    ticker: "VOLV-B.ST",
    name: "Volvo B",
    currency: "SEK",
    regularMarketPrice: 312.7,
    regularMarketChange: 2.48,
    regularMarketChangePercent: 0.8,
    regularMarketVolume: 1_580_000,
    averageDailyVolume3Month: 2_100_000,
    fiftyTwoWeekHigh: 335.0,
    fiftyTwoWeekLow: 248.0,
    marketState: "CLOSED",
  },
  {
    ticker: "SWED-A.ST",
    name: "Swedbank A",
    currency: "SEK",
    regularMarketPrice: 218.4,
    regularMarketChange: -1.56,
    regularMarketChangePercent: -0.7,
    regularMarketVolume: 1_980_000,
    averageDailyVolume3Month: 2_400_000,
    fiftyTwoWeekHigh: 235.0,
    fiftyTwoWeekLow: 182.0,
    marketState: "CLOSED",
  },
  {
    ticker: "SHB-B.ST",
    name: "Handelsbanken B",
    currency: "SEK",
    regularMarketPrice: 124.9,
    regularMarketChange: 0.45,
    regularMarketChangePercent: 0.4,
    regularMarketVolume: 2_300_000,
    averageDailyVolume3Month: 2_700_000,
    fiftyTwoWeekHigh: 132.0,
    fiftyTwoWeekLow: 102.5,
    marketState: "CLOSED",
  },
  {
    ticker: "ATCO-B.ST",
    name: "Atlas Copco B",
    currency: "SEK",
    regularMarketPrice: 162.3,
    regularMarketChange: 1.21,
    regularMarketChangePercent: 0.7,
    regularMarketVolume: 1_870_000,
    averageDailyVolume3Month: 2_100_000,
    fiftyTwoWeekHigh: 178.0,
    fiftyTwoWeekLow: 138.5,
    marketState: "REGULAR",
  },
  {
    ticker: "HM-B.ST",
    name: "H&M B",
    currency: "SEK",
    regularMarketPrice: 153.6,
    regularMarketChange: -3.62,
    regularMarketChangePercent: -2.3,
    regularMarketVolume: 3_400_000,
    averageDailyVolume3Month: 3_900_000,
    fiftyTwoWeekHigh: 198.0,
    fiftyTwoWeekLow: 142.0,
    marketState: "POST",
  },
];

const ANALYSIS: StockAnalysis[] = [
  {
    ticker: "NVDA",
    rating: "🚀 TO THE MOON",
    sentiment: "moon",
    comment: "Jensen printing tendies, AI apes feast tonight",
  },
  {
    ticker: "TSLA",
    rating: "🔥 YOLO CALL",
    sentiment: "moon",
    comment: "Elon tweeted, robotaxis loaded, full port long",
  },
  {
    ticker: "GME",
    rating: "📉 GET REKT",
    sentiment: "rekt",
    comment: "Pump dumped, paper hands fleeing, bagholders crying",
  },
  {
    ticker: "PLTR",
    rating: "📈 BULLISH AF",
    sentiment: "up",
    comment: "Karp's army marching, government tendies incoming",
  },
  {
    ticker: "AMD",
    rating: "📈 BULLISH AF",
    sentiment: "up",
    comment: "Lisa Su grinding, MI300 narrative still hot",
  },
  {
    ticker: "COIN",
    rating: "⚠️ TURBULENCE",
    sentiment: "down",
    comment: "BTC dipping, Coinbase apes nervous but holding",
  },
  {
    ticker: "MSTR",
    rating: "💎 DIAMOND HANDS",
    sentiment: "up",
    comment: "Saylor stacking sats, leveraged BTC printer",
  },
  {
    ticker: "INVE-B.ST",
    rating: "💎 DIAMOND HANDS",
    sentiment: "up",
    comment: "Wallenberg flex, blue chip diamond hands",
  },
  {
    ticker: "VOLV-B.ST",
    rating: "📈 BULLISH AF",
    sentiment: "up",
    comment: "Trucks rolling, industrial apes accumulating quietly",
  },
  {
    ticker: "SWED-A.ST",
    rating: "⚠️ TURBULENCE",
    sentiment: "down",
    comment: "Banking sideways, mild bagholder vibes",
  },
  {
    ticker: "SHB-B.ST",
    rating: "💎 DIAMOND HANDS",
    sentiment: "up",
    comment: "Stadshypotek printing, conservative apes win again",
  },
  {
    ticker: "ATCO-B.ST",
    rating: "💎 DIAMOND HANDS",
    sentiment: "up",
    comment: "Compressors compressing, comfortable hold forever",
  },
  {
    ticker: "HM-B.ST",
    rating: "📉 GET REKT",
    sentiment: "down",
    comment: "Fast fashion fading, paper bag holders eternal",
  },
];

export function getMockData(): StoredData {
  const now = Date.now();
  return {
    stocks: STOCKS,
    analysis: {
      stocks: ANALYSIS,
      overallMood:
        "Wall Street apes ripping faces off — Jensen prints, Elon yolos, GME dumps. Stockholm sleeps through it.",
      biggestWinner: "NVDA",
      biggestLoser: "GME",
    },
    updatedAt: new Date(now).toISOString(),
    lastFetch: now,
  };
}
