import type { StockAnalysis, StockPrice, StoredData } from "./types";

const STOCKS: StockPrice[] = [
  {
    ticker: "NET",
    name: "Cloudflare",
    currency: "USD",
    regularMarketPrice: 78.45,
    regularMarketChange: 5.27,
    regularMarketChangePercent: 7.2,
    regularMarketVolume: 12_540_000,
    averageDailyVolume3Month: 8_410_000,
    fiftyTwoWeekHigh: 81.0,
    fiftyTwoWeekLow: 52.1,
    marketState: "REGULAR",
  },
  {
    ticker: "DDOG",
    name: "Datadog",
    currency: "USD",
    regularMarketPrice: 122.3,
    regularMarketChange: 2.16,
    regularMarketChangePercent: 1.8,
    regularMarketVolume: 4_120_000,
    averageDailyVolume3Month: 3_700_000,
    fiftyTwoWeekHigh: 152.0,
    fiftyTwoWeekLow: 95.4,
    marketState: "REGULAR",
  },
  {
    ticker: "IONQ",
    name: "IonQ",
    currency: "USD",
    regularMarketPrice: 9.42,
    regularMarketChange: -0.89,
    regularMarketChangePercent: -8.6,
    regularMarketVolume: 22_300_000,
    averageDailyVolume3Month: 11_500_000,
    fiftyTwoWeekHigh: 19.5,
    fiftyTwoWeekLow: 6.85,
    marketState: "REGULAR",
  },
  {
    ticker: "SHOP",
    name: "Shopify",
    currency: "USD",
    regularMarketPrice: 96.85,
    regularMarketChange: 4.17,
    regularMarketChangePercent: 4.5,
    regularMarketVolume: 7_840_000,
    averageDailyVolume3Month: 6_200_000,
    fiftyTwoWeekHigh: 112.4,
    fiftyTwoWeekLow: 65.0,
    marketState: "PRE",
  },
  {
    ticker: "GOOGL",
    name: "Alphabet A",
    currency: "USD",
    regularMarketPrice: 167.2,
    regularMarketChange: 2.47,
    regularMarketChangePercent: 1.5,
    regularMarketVolume: 18_900_000,
    averageDailyVolume3Month: 22_000_000,
    fiftyTwoWeekHigh: 195.0,
    fiftyTwoWeekLow: 130.5,
    marketState: "REGULAR",
  },
  {
    ticker: "INVE-B.ST",
    name: "Investor B",
    currency: "SEK",
    regularMarketPrice: 285.4,
    regularMarketChange: 5.87,
    regularMarketChangePercent: 2.1,
    regularMarketVolume: 1_240_000,
    averageDailyVolume3Month: 1_800_000,
    fiftyTwoWeekHigh: 302.0,
    fiftyTwoWeekLow: 240.5,
    marketState: "REGULAR",
  },
  {
    ticker: "SWED-A.ST",
    name: "Swedbank A",
    currency: "SEK",
    regularMarketPrice: 209.5,
    regularMarketChange: -1.27,
    regularMarketChangePercent: -0.6,
    regularMarketVolume: 2_100_000,
    averageDailyVolume3Month: 2_400_000,
    fiftyTwoWeekHigh: 228.0,
    fiftyTwoWeekLow: 188.0,
    marketState: "CLOSED",
  },
  {
    ticker: "ABB.ST",
    name: "ABB",
    currency: "SEK",
    regularMarketPrice: 587.2,
    regularMarketChange: 6.95,
    regularMarketChangePercent: 1.2,
    regularMarketVolume: 1_540_000,
    averageDailyVolume3Month: 1_700_000,
    fiftyTwoWeekHigh: 608.0,
    fiftyTwoWeekLow: 480.0,
    marketState: "REGULAR",
  },
  {
    ticker: "SAND.ST",
    name: "Sandvik",
    currency: "SEK",
    regularMarketPrice: 228.1,
    regularMarketChange: 4.04,
    regularMarketChangePercent: 1.8,
    regularMarketVolume: 1_980_000,
    averageDailyVolume3Month: 2_100_000,
    fiftyTwoWeekHigh: 240.0,
    fiftyTwoWeekLow: 195.5,
    marketState: "REGULAR",
  },
  {
    ticker: "ASSA-B.ST",
    name: "Assa Abloy B",
    currency: "SEK",
    regularMarketPrice: 332.6,
    regularMarketChange: -5.06,
    regularMarketChangePercent: -1.5,
    regularMarketVolume: 980_000,
    averageDailyVolume3Month: 1_200_000,
    fiftyTwoWeekHigh: 358.0,
    fiftyTwoWeekLow: 295.0,
    marketState: "REGULAR",
  },
  {
    ticker: "HEICO.ST",
    name: "Heico",
    currency: "SEK",
    regularMarketPrice: 187.4,
    regularMarketChange: 0.37,
    regularMarketChangePercent: 0.2,
    regularMarketVolume: 24_000,
    averageDailyVolume3Month: 30_000,
    fiftyTwoWeekHigh: 195.0,
    fiftyTwoWeekLow: 162.0,
    marketState: "POST",
  },
  {
    ticker: "PARADOX.ST",
    name: "Paradox Interactive",
    currency: "SEK",
    regularMarketPrice: 224.8,
    regularMarketChange: -7.43,
    regularMarketChangePercent: -3.2,
    regularMarketVolume: 410_000,
    averageDailyVolume3Month: 320_000,
    fiftyTwoWeekHigh: 285.0,
    fiftyTwoWeekLow: 195.0,
    marketState: "REGULAR",
  },
];

const ANALYSIS: StockAnalysis[] = [
  {
    ticker: "NET",
    rating: "🚀 TO THE MOON",
    sentiment: "moon",
    comment: "Cloudflare printing tendies, apes feast tonight",
  },
  {
    ticker: "DDOG",
    rating: "📈 BULLISH AF",
    sentiment: "up",
    comment: "Observability bull run, diamond hands holding",
  },
  {
    ticker: "IONQ",
    rating: "📉 GET REKT",
    sentiment: "rekt",
    comment: "Quantum apes capitulating, bagholders crying tonight",
  },
  {
    ticker: "SHOP",
    rating: "🔥 YOLO CALL",
    sentiment: "moon",
    comment: "Merchant kings stacking, all-time high in sight",
  },
  {
    ticker: "GOOGL",
    rating: "💎 DIAMOND HANDS",
    sentiment: "up",
    comment: "Big G grinding higher, AI moat impenetrable",
  },
  {
    ticker: "INVE-B.ST",
    rating: "📈 BULLISH AF",
    sentiment: "up",
    comment: "Wallenberg flex, blue chip diamond hands",
  },
  {
    ticker: "SWED-A.ST",
    rating: "⚠️ TURBULENCE",
    sentiment: "neutral",
    comment: "Banking sideways, neither tendies nor pain",
  },
  {
    ticker: "ABB.ST",
    rating: "💎 DIAMOND HANDS",
    sentiment: "up",
    comment: "Industrial grind, robots making quiet moves",
  },
  {
    ticker: "SAND.ST",
    rating: "📈 BULLISH AF",
    sentiment: "up",
    comment: "Mining tools printing, swedish steel goes brrr",
  },
  {
    ticker: "ASSA-B.ST",
    rating: "⚠️ TURBULENCE",
    sentiment: "down",
    comment: "Locks unlocking mild losses, bagholder vibes",
  },
  {
    ticker: "HEICO.ST",
    rating: "⚠️ TURBULENCE",
    sentiment: "neutral",
    comment: "Range bound, market shrugs, keep holding",
  },
  {
    ticker: "PARADOX.ST",
    rating: "📉 GET REKT",
    sentiment: "down",
    comment: "Crusader Kings dethroned, paper hands fleeing",
  },
];

export function getMockData(): StoredData {
  const now = Date.now();
  return {
    stocks: STOCKS,
    analysis: {
      stocks: ANALYSIS,
      overallMood:
        "Stockholm sleepy, Wall Street apes full-port long Cloudflare while IonQ longs get absolutely vaporized.",
      biggestWinner: "NET",
      biggestLoser: "IONQ",
    },
    updatedAt: new Date(now).toISOString(),
    lastFetch: now,
  };
}
