import type { StockAnalysis, StockPrice, StoredData } from "./types";

const STOCKS: StockPrice[] = [
  // ============== US — WSB darlings ==============
  {
    ticker: "NVDA",
    name: "Nvidia",
    currency: "USD",
    regularMarketPrice: 142.85,
    regularMarketChange: 9.07,
    regularMarketChangePercent: 6.8,
    regularMarketVolume: 235_000_000,
    averageDailyVolume3Month: 180_000_000,
    fiftyTwoWeekHigh: 148.0,
    fiftyTwoWeekLow: 84.5,
    marketState: "REGULAR",
  },
  {
    ticker: "TSLA",
    name: "Tesla",
    currency: "USD",
    regularMarketPrice: 428.6,
    regularMarketChange: 19.61,
    regularMarketChangePercent: 4.8,
    regularMarketVolume: 92_000_000,
    averageDailyVolume3Month: 78_000_000,
    fiftyTwoWeekHigh: 488.5,
    fiftyTwoWeekLow: 178.0,
    marketState: "REGULAR",
  },
  {
    ticker: "GME",
    name: "GameStop",
    currency: "USD",
    regularMarketPrice: 22.85,
    regularMarketChange: -2.32,
    regularMarketChangePercent: -9.2,
    regularMarketVolume: 18_500_000,
    averageDailyVolume3Month: 9_400_000,
    fiftyTwoWeekHigh: 64.83,
    fiftyTwoWeekLow: 9.95,
    marketState: "REGULAR",
  },
  {
    ticker: "PLTR",
    name: "Palantir",
    currency: "USD",
    regularMarketPrice: 72.4,
    regularMarketChange: 2.18,
    regularMarketChangePercent: 3.1,
    regularMarketVolume: 45_000_000,
    averageDailyVolume3Month: 62_000_000,
    fiftyTwoWeekHigh: 84.0,
    fiftyTwoWeekLow: 21.0,
    marketState: "REGULAR",
  },
  {
    ticker: "AMD",
    name: "AMD",
    currency: "USD",
    regularMarketPrice: 132.6,
    regularMarketChange: 2.34,
    regularMarketChangePercent: 1.8,
    regularMarketVolume: 38_000_000,
    averageDailyVolume3Month: 45_000_000,
    fiftyTwoWeekHigh: 187.0,
    fiftyTwoWeekLow: 116.0,
    marketState: "PRE",
  },
  {
    ticker: "COIN",
    name: "Coinbase",
    currency: "USD",
    regularMarketPrice: 278.4,
    regularMarketChange: -4.24,
    regularMarketChangePercent: -1.5,
    regularMarketVolume: 11_200_000,
    averageDailyVolume3Month: 9_800_000,
    fiftyTwoWeekHigh: 343.0,
    fiftyTwoWeekLow: 142.5,
    marketState: "REGULAR",
  },
  {
    ticker: "MSTR",
    name: "MicroStrategy",
    currency: "USD",
    regularMarketPrice: 382.1,
    regularMarketChange: 4.53,
    regularMarketChangePercent: 1.2,
    regularMarketVolume: 14_500_000,
    averageDailyVolume3Month: 18_200_000,
    fiftyTwoWeekHigh: 543.0,
    fiftyTwoWeekLow: 184.0,
    marketState: "REGULAR",
  },
  {
    ticker: "SHOP",
    name: "Shopify",
    currency: "USD",
    regularMarketPrice: 110.4,
    regularMarketChange: 2.7,
    regularMarketChangePercent: 2.5,
    regularMarketVolume: 7_840_000,
    averageDailyVolume3Month: 6_200_000,
    fiftyTwoWeekHigh: 0,
    fiftyTwoWeekLow: 0,
    marketState: "REGULAR",
  },
  {
    ticker: "NET",
    name: "Cloudflare",
    currency: "USD",
    regularMarketPrice: 124.5,
    regularMarketChange: 4.56,
    regularMarketChangePercent: 3.8,
    regularMarketVolume: 12_500_000,
    averageDailyVolume3Month: 8_400_000,
    fiftyTwoWeekHigh: 0,
    fiftyTwoWeekLow: 0,
    marketState: "REGULAR",
  },
  {
    ticker: "KLAR",
    name: "Klarna Group",
    currency: "USD",
    regularMarketPrice: 48.2,
    regularMarketChange: 0.71,
    regularMarketChangePercent: 1.5,
    regularMarketVolume: 4_200_000,
    averageDailyVolume3Month: 5_100_000,
    fiftyTwoWeekHigh: 0,
    fiftyTwoWeekLow: 0,
    marketState: "REGULAR",
  },
  // ============== Sweden — ISK staples ==============
  {
    ticker: "INVE-B.ST",
    name: "Investor B",
    currency: "SEK",
    regularMarketPrice: 285.4,
    regularMarketChange: 3.94,
    regularMarketChangePercent: 1.4,
    regularMarketVolume: 1_240_000,
    averageDailyVolume3Month: 1_800_000,
    fiftyTwoWeekHigh: 302.0,
    fiftyTwoWeekLow: 240.5,
    marketState: "REGULAR",
  },
  {
    ticker: "VOLV-B.ST",
    name: "Volvo B",
    currency: "SEK",
    regularMarketPrice: 312.7,
    regularMarketChange: 2.48,
    regularMarketChangePercent: 0.8,
    regularMarketVolume: 1_580_000,
    averageDailyVolume3Month: 2_100_000,
    fiftyTwoWeekHigh: 335.0,
    fiftyTwoWeekLow: 248.0,
    marketState: "CLOSED",
  },
  {
    ticker: "SWED-A.ST",
    name: "Swedbank A",
    currency: "SEK",
    regularMarketPrice: 218.4,
    regularMarketChange: -1.56,
    regularMarketChangePercent: -0.7,
    regularMarketVolume: 1_980_000,
    averageDailyVolume3Month: 2_400_000,
    fiftyTwoWeekHigh: 235.0,
    fiftyTwoWeekLow: 182.0,
    marketState: "CLOSED",
  },
  {
    ticker: "SHB-B.ST",
    name: "Handelsbanken B",
    currency: "SEK",
    regularMarketPrice: 124.9,
    regularMarketChange: 0.45,
    regularMarketChangePercent: 0.4,
    regularMarketVolume: 2_300_000,
    averageDailyVolume3Month: 2_700_000,
    fiftyTwoWeekHigh: 132.0,
    fiftyTwoWeekLow: 102.5,
    marketState: "CLOSED",
  },
  {
    ticker: "ATCO-B.ST",
    name: "Atlas Copco B",
    currency: "SEK",
    regularMarketPrice: 162.3,
    regularMarketChange: 1.21,
    regularMarketChangePercent: 0.7,
    regularMarketVolume: 1_870_000,
    averageDailyVolume3Month: 2_100_000,
    fiftyTwoWeekHigh: 178.0,
    fiftyTwoWeekLow: 138.5,
    marketState: "REGULAR",
  },
  {
    ticker: "HM-B.ST",
    name: "H&M B",
    currency: "SEK",
    regularMarketPrice: 153.6,
    regularMarketChange: -3.62,
    regularMarketChangePercent: -2.3,
    regularMarketVolume: 3_400_000,
    averageDailyVolume3Month: 3_900_000,
    fiftyTwoWeekHigh: 198.0,
    fiftyTwoWeekLow: 142.0,
    marketState: "POST",
  },
  {
    ticker: "DOM.ST",
    name: "Dometic Group",
    currency: "SEK",
    regularMarketPrice: 33.28,
    regularMarketChange: 0.42,
    regularMarketChangePercent: 1.3,
    regularMarketVolume: 1_120_000,
    averageDailyVolume3Month: 1_400_000,
    fiftyTwoWeekHigh: 0,
    fiftyTwoWeekLow: 0,
    marketState: "REGULAR",
  },
  {
    ticker: "BINV.ST",
    name: "BioInvent",
    currency: "SEK",
    regularMarketPrice: 23.15,
    regularMarketChange: -0.85,
    regularMarketChangePercent: -3.5,
    regularMarketVolume: 540_000,
    averageDailyVolume3Month: 720_000,
    fiftyTwoWeekHigh: 0,
    fiftyTwoWeekLow: 0,
    marketState: "REGULAR",
  },
  {
    ticker: "THULE.ST",
    name: "Thule Group",
    currency: "SEK",
    regularMarketPrice: 240.8,
    regularMarketChange: 4.85,
    regularMarketChangePercent: 2.1,
    regularMarketVolume: 380_000,
    averageDailyVolume3Month: 510_000,
    fiftyTwoWeekHigh: 0,
    fiftyTwoWeekLow: 0,
    marketState: "REGULAR",
  },
  {
    ticker: "CAST.ST",
    name: "Castellum",
    currency: "SEK",
    regularMarketPrice: 120.8,
    regularMarketChange: -1.32,
    regularMarketChangePercent: -1.1,
    regularMarketVolume: 1_240_000,
    averageDailyVolume3Month: 1_500_000,
    fiftyTwoWeekHigh: 0,
    fiftyTwoWeekLow: 0,
    marketState: "REGULAR",
  },
  {
    ticker: "NIBE-B.ST",
    name: "Nibe Industrier B",
    currency: "SEK",
    regularMarketPrice: 42.42,
    regularMarketChange: 0.91,
    regularMarketChangePercent: 2.2,
    regularMarketVolume: 4_200_000,
    averageDailyVolume3Month: 5_100_000,
    fiftyTwoWeekHigh: 0,
    fiftyTwoWeekLow: 0,
    marketState: "REGULAR",
  },
  {
    ticker: "DICOT.ST",
    name: "Dicot Pharma",
    currency: "SEK",
    regularMarketPrice: 0.2684,
    regularMarketChange: -0.0382,
    regularMarketChangePercent: -12.5,
    regularMarketVolume: 8_300_000,
    averageDailyVolume3Month: 4_200_000,
    fiftyTwoWeekHigh: 0,
    fiftyTwoWeekLow: 0,
    marketState: "REGULAR",
  },
  {
    ticker: "VPLAY-B.ST",
    name: "Viaplay Group B",
    currency: "SEK",
    regularMarketPrice: 1.85,
    regularMarketChange: -0.08,
    regularMarketChangePercent: -4.2,
    regularMarketVolume: 6_400_000,
    averageDailyVolume3Month: 4_800_000,
    fiftyTwoWeekHigh: 0,
    fiftyTwoWeekLow: 0,
    marketState: "REGULAR",
  },
];

const ANALYSIS: StockAnalysis[] = [
  {
    ticker: "NVDA",
    rating: "🚀 TO THE MOON",
    sentiment: "moon",
    comment: "Jensen printing tendies, AI apes feast tonight",
  },
  {
    ticker: "TSLA",
    rating: "🔥 YOLO CALL",
    sentiment: "moon",
    comment: "Elon tweeted, robotaxis loaded, full port long",
  },
  {
    ticker: "GME",
    rating: "📉 GET REKT",
    sentiment: "rekt",
    comment: "Pump dumped, paper hands fleeing, bagholders crying",
  },
  {
    ticker: "PLTR",
    rating: "📈 BULLISH AF",
    sentiment: "up",
    comment: "Karp's army marching, government tendies incoming",
  },
  {
    ticker: "AMD",
    rating: "📈 BULLISH AF",
    sentiment: "up",
  },
  {
    ticker: "COIN",
    rating: "⚠️ TURBULENCE",
    sentiment: "down",
  },
  {
    ticker: "MSTR",
    rating: "💎 DIAMOND HANDS",
    sentiment: "up",
  },
  {
    ticker: "SHOP",
    rating: "📈 BULLISH AF",
    sentiment: "up",
    comment: "Merchants printing tendies, all-time high incoming",
  },
  {
    ticker: "NET",
    rating: "🚀 TO THE MOON",
    sentiment: "moon",
    comment: "Chris's Cloudflare ripping faces, AI infra moon",
  },
  {
    ticker: "KLAR",
    rating: "📈 BULLISH AF",
    sentiment: "up",
  },
  {
    ticker: "INVE-B.ST",
    rating: "💎 DIAMOND HANDS",
    sentiment: "up",
  },
  {
    ticker: "VOLV-B.ST",
    rating: "📈 BULLISH AF",
    sentiment: "up",
  },
  {
    ticker: "SWED-A.ST",
    rating: "⚠️ TURBULENCE",
    sentiment: "down",
  },
  {
    ticker: "SHB-B.ST",
    rating: "💎 DIAMOND HANDS",
    sentiment: "up",
  },
  {
    ticker: "ATCO-B.ST",
    rating: "💎 DIAMOND HANDS",
    sentiment: "up",
  },
  {
    ticker: "HM-B.ST",
    rating: "📉 GET REKT",
    sentiment: "down",
    comment: "Fast fashion fading, paper bag holders eternal",
  },
  {
    ticker: "DOM.ST",
    rating: "📈 BULLISH AF",
    sentiment: "up",
  },
  {
    ticker: "BINV.ST",
    rating: "⚠️ TURBULENCE",
    sentiment: "down",
    comment: "Biotech rollercoaster, FDA gods unhappy today",
  },
  {
    ticker: "THULE.ST",
    rating: "💎 DIAMOND HANDS",
    sentiment: "up",
    comment: "Roof boxes printing tendies, Volvo dad approves",
  },
  {
    ticker: "CAST.ST",
    rating: "⚠️ TURBULENCE",
    sentiment: "down",
  },
  {
    ticker: "NIBE-B.ST",
    rating: "📈 BULLISH AF",
    sentiment: "up",
    comment: "Heat pumps go brrr, Swedish winter saviour",
  },
  {
    ticker: "DICOT.ST",
    rating: "🔥 YOLO CALL",
    sentiment: "rekt",
    comment: "Oskar's Dicot apes vaporized at 25 öre",
  },
  {
    ticker: "VPLAY-B.ST",
    rating: "📉 GET REKT",
    sentiment: "down",
    comment: "Eric's Viaplay sinking, paper hands fleeing",
  },
];

export function getMockData(): StoredData {
  const now = Date.now();
  return {
    stocks: STOCKS,
    analysis: {
      stocks: ANALYSIS,
      overallMood:
        "Chris's Cloudflare moons while Eric's Viaplay tanks and Oskar's Dicot apes get fully vaporized — typical Tuesday in the trenches.",
      biggestWinner: "NVDA",
      biggestLoser: "DICOT.ST",
    },
    updatedAt: new Date(now).toISOString(),
    lastFetch: now,
  };
}
