import { deriveRating, deriveSentiment } from "./derive";
import { PEOPLE, TICKERS, type Ticker } from "./tickers";
import type {
  Sentiment,
  StockAnalysis,
  StockPrice,
} from "./types";

/**
 * Static per-ticker WSB comments, bucketed by sentiment band. Drives the
 * comment on each stock card — replaces the per-tick Haiku analyzer call.
 *
 * Why static:
 *   The mood headline is generated by Sonnet (lib/generateMood.ts) on a
 *   stricter event-driven cadence. The per-ticker comments were the cost
 *   driver of the Anthropic bill and the most repetitive output —
 *   pre-authored one-liners per ticker × sentiment bucket give comparable
 *   density without the per-tick API spend.
 *
 * Buckets align with `deriveSentiment`:
 *   moon     pct > 5
 *   up       0.5 < pct ≤ 5
 *   (neutral pct ∈ [-0.5, 0.5] — intentionally omitted; quiet days =
 *            silent cards, no filler. Same rule the Haiku prompt
 *            enforced: "silence is better than filler.")
 *   down    -5 < pct ≤ -0.5
 *   rekt     pct ≤ -5
 *
 * Owner attribution is templated, not baked. The `{owner}` placeholder
 * expands at lookup time using each ticker's CURRENT owners from
 * lib/tickers.ts — so editing the owners array there (new friend, swap
 * between users, dropping a ticker) auto-syncs every comment without
 * touching this file. Resolves as:
 *   1 owner   → "Chris's "          (or whatever the friend's first name is)
 *   2+ owners → "the gang's "       (or the override below)
 *   0 owners  → ""                   (no possessive prefix)
 *
 * The lines were seeded from each ticker's old `context` blurb, so the
 * meme angle is preserved (Wallenberg / heat pumps / liquid-cooled GPUs
 * / Saylor leverage / Reddit-hosts-WSB-itself etc.) — just frozen at
 * authoring time instead of regenerated every cron tick.
 */

/**
 * Custom collective phrase for multi-owner tickers. Anything not listed
 * here uses "the gang" as the default. Override sparingly — keep the
 * default for most so the dashboard doesn't read like a bingo card.
 */
const COLLECTIVE_OVERRIDES: Record<string, string> = {
  "INVE-B.ST": "the syndicate", // 3-owner Wallenberg bag deserves the Wall Street operator vibe
};

type MessageTable = Partial<Record<Sentiment, string>>;

/**
 * Per-ticker, per-sentiment one-liners. Lines ≤14 words, WSB voice,
 * owner-anchored via `{owner}` where attribution adds flavor. Tickers
 * without an `owners` entry omit the placeholder — the line reads
 * straight without a possessive prefix.
 */
const MESSAGES: Record<string, MessageTable> = {
  // ============== Swedish (Avanza) ==============

  "INVE-B.ST": {
    moon: "{owner}Investor B mooning — Wallenberg empire printing tendies",
    up: "{owner}Investor B grinding green, ABB+AstraZeneca compounder humming",
    down: "{owner}Investor B fading, NAV premium softening",
    rekt: "{owner}Investor B rekt — even Wallenbergs bleed sometimes",
  },
  "VOLV-B.ST": {
    moon: "Volvo trucks mooning, freight cycle finally printing",
    up: "Volvo grinding green, the truck Volvo doing truck things",
    down: "Volvo slipping, capex jitters in trucking",
    rekt: "Volvo rekt — freight cycle eating its own trucks",
  },
  "SWED-A.ST": {
    moon: "{owner}Swedbank mooning, Riksbank rates printing tendies",
    up: "{owner}Swedbank grinding green, mortgage book purring",
    down: "{owner}Swedbank slipping, housing wobble whispering",
    rekt: "{owner}Swedbank rekt — Oskar's day job paying in pain today",
  },
  "SHB-B.ST": {
    moon: "{owner}Handelsbanken mooning, decentralized branches printing",
    up: "{owner}Handelsbanken grinding higher, conservative banking flexing",
    down: "{owner}Handelsbanken slipping, mortgages sweating",
    rekt: "{owner}Handelsbanken rekt — Chris's day job hurting his bag",
  },
  "ATCO-B.ST": {
    moon: "Atlas Copco mooning, industrial compressors humming",
    up: "Atlas Copco grinding green, Buffett-Swedish-compounder energy",
    down: "Atlas Copco slipping, industrial capex pause",
    rekt: "Atlas Copco rekt — even compounders crater sometimes",
  },
  "HM-B.ST": {
    moon: "H&M mooning, turnaround whispers louder than Zara",
    up: "H&M grinding green, fast fashion finding a pulse",
    down: "H&M slipping, Shein eating lunch again",
    rekt: "H&M rekt — national institution speedrunning irrelevance",
  },
  "DOM.ST": {
    moon: "{owner}Dometic mooning, RV cycle finally printing",
    up: "{owner}Dometic grinding green, outdoor leisure tendies",
    down: "{owner}Dometic slipping, RV hangover continuing",
    rekt: "{owner}Dometic rekt — post-COVID RV cycle still crushing",
  },
  "BINV.ST": {
    moon: "{owner}BioInvent mooning — Big Pharma circling",
    up: "{owner}BioInvent grinding green, oncology pipeline humming",
    down: "{owner}BioInvent slipping, biotech mood cooling",
    rekt: "{owner}BioInvent rekt — multiple shots on goal, today missed",
  },
  "THULE.ST": {
    moon: "{owner}Thule mooning, premium outdoor printing tendies",
    up: "{owner}Thule grinding green, roof boxes selling themselves",
    down: "{owner}Thule slipping, consumer durables wobbling",
    rekt: "{owner}Thule rekt — bike racks aren't recession-proof",
  },
  "CAST.ST": {
    moon: "Castellum mooning, real estate finds a bid",
    up: "Castellum grinding green, debt narrative softening",
    down: "Castellum slipping, offices still suspicious",
    rekt: "Castellum rekt — commercial real estate bagholder confirmed",
  },
  "NIBE-B.ST": {
    moon: "{owner}Nibe mooning, heat pumps back in fashion",
    up: "{owner}Nibe grinding green, energy crisis nostalgia",
    down: "{owner}Nibe slipping, subsidy hangover lingering",
    rekt: "{owner}Nibe rekt — heat pumps cooled hard",
  },
  "DICOT.ST": {
    // HUMOR PERMISSION applies — anatomical double entendres expected,
    // paired with the pharma reality (LIB-01, dilution, Phase 2b wait).
    moon: "{owner}Dicot getting it up — LIB-01 staying hard for weeks",
    up: "{owner}Dicot pumping, Phase 2b wood lengthening",
    down: "{owner}Dicot drooping, dilution softening the climax",
    rekt: "{owner}Dicot can't keep it up — 210M rights issue dropping",
  },
  "VPLAY-B.ST": {
    moon: "{owner}Viaplay mooning — turnaround copium uncorked",
    up: "{owner}Viaplay grinding green, Nordic retreat working",
    down: "{owner}Viaplay slipping, post-expansion hangover continuing",
    rekt: "{owner}Viaplay rekt — pure unrelenting bagholder energy",
  },
  "INTRUM.ST": {
    moon: "{owner}Intrum mooning, debt collectors printing on misery",
    up: "{owner}Intrum grinding green, recession copium printing",
    down: "{owner}Intrum slipping, balance sheet jitters",
    rekt: "{owner}Intrum rekt — turnaround speedrunning failure",
  },
  "HACK.ST": {
    moon: "{owner}Hacksaw spinning jackpots, US states printing tendies",
    up: "{owner}Hacksaw grinding green, slot RTPs pumping",
    down: "{owner}Hacksaw slipping, jackpot drought hitting",
    rekt: "{owner}Hacksaw rekt — slot machines paying out red today",
  },
  "BETS-B.ST": {
    moon: "{owner}Betsson mooning, sportsbook running hot",
    up: "{owner}Betsson grinding green, gambling cash printing",
    down: "{owner}Betsson slipping, regulatory headlines spooking",
    rekt: "{owner}Betsson rekt — the house lost a hand today",
  },
  "LUND-B.ST": {
    moon: "{owner}Lundbergs mooning, old-money discipline printing",
    up: "{owner}Lundbergs grinding green, NAV discount narrowing",
    down: "{owner}Lundbergs slipping, holdco discount widening",
    rekt: "{owner}Lundbergs rekt — even Lundbergs can bleed",
  },
  "LATO-B.ST": {
    moon: "{owner}Latour mooning, Assa Abloy + Tomra printing",
    up: "{owner}Latour grinding green, industrial compounder humming",
    down: "{owner}Latour slipping, premium NAV softening",
    rekt: "{owner}Latour rekt — industrial holdco caught a falling Tomra",
  },
  "SES.ST": {
    moon: "{owner}SES mooning, tire pyrolysis suddenly making sense",
    up: "{owner}SES grinding green, Michelin partnership hum",
    down: "{owner}SES slipping, commercial ramp delayed again",
    rekt: "{owner}SES rekt — penny stock pyrolysis doing penny stock things",
  },
  "ACCON.ST": {
    moon: "{owner}Acconeer mooning, radar design win landed",
    up: "{owner}Acconeer grinding green, PCR chips finding traction",
    down: "{owner}Acconeer slipping, revenue lumps showing",
    rekt: "{owner}Acconeer rekt — small-cap chip play crashing back to earth",
  },
  "FLAT-B.ST": {
    moon: "{owner}Flat Capital mooning — Klarna IPO copium uncorked",
    up: "{owner}Flat Capital grinding green, private-tech wrapper pumping",
    down: "{owner}Flat Capital slipping, NAV discount widening",
    rekt: "{owner}Flat Capital rekt — Klarna delay still stinging",
  },
  // ============== US (Finnhub) ==============

  "NVDA": {
    moon: "NVDA mooning, Jensen's leather jacket selling itself",
    up: "NVDA grinding green, AI capex printing again",
    down: "NVDA slipping, AI hype cooling slightly",
    rekt: "NVDA rekt — even the altar can crack",
  },
  "TSLA": {
    moon: "TSLA mooning, an Elon tweet sent it",
    up: "TSLA grinding green, FSD copium working today",
    down: "TSLA slipping, delivery doubts surfacing",
    rekt: "TSLA rekt — Optimus jokes writing themselves",
  },
  "GME": {
    moon: "GME mooning — apes never died",
    up: "GME grinding green, kitty hint making rounds",
    down: "GME slipping, brick-and-mortar reality leaking through",
    rekt: "GME rekt — sacred ground takes a hit",
  },
  "PLTR": {
    moon: "{owner}Palantir mooning, Karp ranting all the way up",
    up: "{owner}Palantir grinding green, government contract whispers",
    down: "{owner}Palantir slipping, valuation gravity kicking in",
    rekt: "{owner}Palantir rekt — multiple compression hurting the heavy bag",
  },
  "AMD": {
    moon: "AMD mooning, MI350 ramp finally believed",
    up: "AMD grinding green, Lisa Su execution flexing",
    down: "AMD slipping, NVDA shadow long again",
    rekt: "AMD rekt — perpetual challenger remembered as second",
  },
  "COIN": {
    moon: "COIN mooning with BTC, the casino opens green",
    up: "COIN grinding green, trading volume waking up",
    down: "COIN slipping, crypto vibes dimming",
    rekt: "COIN rekt — BTC drag pulling the exchange down",
  },
  "MSTR": {
    moon: "MSTR mooning, Saylor adding leverage to leverage",
    up: "MSTR grinding green, BTC proxy doing BTC proxy things",
    down: "MSTR slipping, premium-to-NAV compressing",
    rekt: "MSTR rekt — leveraged BTC bag working both ways today",
  },
  "SHOP": {
    moon: "{owner}Shopify mooning, merchant flywheel printing",
    up: "{owner}Shopify grinding green, Shop Pay flexing",
    down: "{owner}Shopify slipping, consumer spending wobble",
    rekt: "{owner}Shopify rekt — e-commerce SaaS losing its tendies",
  },
  "NET": {
    moon: "{owner}Cloudflare mooning, Workers AI moment landing",
    up: "{owner}Cloudflare grinding green, Matthew Prince blog working",
    down: "{owner}Cloudflare slipping, multiple compression nibbling",
    rekt: "{owner}Cloudflare rekt — high-multiple gravity hurting",
  },
  "QBTS": {
    moon: "{owner}D-Wave mooning, quantum cult got a contract",
    up: "{owner}D-Wave grinding green, annealing copium printing",
    down: "{owner}D-Wave slipping, quantum hype cooling",
    rekt: "{owner}D-Wave rekt — speculative quantum doing speculative things",
  },
  "GOOG": {
    moon: "{owner}Alphabet mooning, Gemini benchmark dropped fire",
    up: "{owner}Alphabet grinding green, Search moat holding",
    down: "{owner}Alphabet slipping, AI threat narrative resurfacing",
    rekt: "{owner}Alphabet rekt — antitrust headlines biting",
  },
  "DDOG": {
    moon: "{owner}Datadog mooning, LLM observability product printing",
    up: "{owner}Datadog grinding green, cloud spend tailwind",
    down: "{owner}Datadog slipping, multiple compression hitting growth SaaS",
    rekt: "{owner}Datadog rekt — boring-reliable broke briefly",
  },
  "DFTX": {
    moon: "{owner}Definium mooning, biotech trial whisper printing",
    up: "{owner}Definium grinding green, small-cap pharma copium",
    down: "{owner}Definium slipping, cap raise jitters lingering",
    rekt: "{owner}Definium rekt — pre-revenue biotech doing pre-revenue things",
  },
  "JOBY": {
    moon: "{owner}Joby mooning, eVTOL hype tank refilled",
    up: "{owner}Joby grinding green, Toyota+Delta names supporting",
    down: "{owner}Joby slipping, FAA timeline doubts",
    rekt: "{owner}Joby rekt — flying taxis grounded again",
  },
  "IONQ": {
    moon: "{owner}IonQ mooning, trapped ions trapping tendies",
    up: "{owner}IonQ grinding green, Microsoft halo helping",
    down: "{owner}IonQ slipping, quantum vibe cooling",
    rekt: "{owner}IonQ rekt — multi-bag-or-zero leaning zero today",
  },
  "RDDT": {
    moon: "{owner}Reddit mooning — the WSB home printing tendies",
    up: "{owner}Reddit grinding green, AI-licensing flywheel humming",
    down: "{owner}Reddit slipping, DAU growth questions resurface",
    rekt: "{owner}Reddit rekt — even the platform that hosts WSB can crash",
  },
};

/**
 * Resolve the `{owner}` placeholder for a ticker using its CURRENT
 * owners — so editing `tickers.ts` (add friend, swap stocks between
 * users, drop an owner) automatically propagates to every comment
 * without needing to touch the message table.
 */
function ownerPrefix(ticker: Ticker): string {
  const owners = ticker.owners ?? [];
  if (owners.length === 1) {
    const first = owners[0]!;
    return `${PEOPLE[first]}'s `;
  }
  if (owners.length >= 2) {
    return `${COLLECTIVE_OVERRIDES[ticker.symbol] ?? "the gang"}'s `;
  }
  return "";
}

function expandTemplate(template: string, ticker: Ticker): string {
  return template.replace(/\{owner\}/g, ownerPrefix(ticker));
}

/**
 * Build the per-ticker analysis payload (rating, sentiment, optional
 * comment) for the current prices. Replaces the per-tick Haiku analyzer
 * call — runs in pure code, every trigger, effectively free.
 *
 * Returns one entry per input price. `comment` is omitted when:
 *   - the ticker has no MESSAGES entry (new ticker, not yet authored), OR
 *   - the move falls into the neutral band (-0.5..0.5%), OR
 *   - the resolved bucket has no line defined for this ticker.
 *
 * Cards render gracefully without a comment in any of those cases.
 */
export function buildStaticComments(prices: StockPrice[]): StockAnalysis[] {
  const tickerMeta = new Map(TICKERS.map((t) => [t.symbol, t]));
  return prices.map((p) => {
    const sentiment = deriveSentiment(p.regularMarketChangePercent);
    const rating = deriveRating(p.regularMarketChangePercent);

    const ticker = tickerMeta.get(p.ticker);
    const table = MESSAGES[p.ticker];
    const template = table ? table[sentiment] : undefined;
    const comment =
      ticker && template ? expandTemplate(template, ticker) : undefined;

    return {
      ticker: p.ticker,
      ...(rating ? { rating } : {}),
      sentiment,
      ...(comment ? { comment } : {}),
    };
  });
}

// Exposed for tests — verifies coverage (every ticker in TICKERS that
// "deserves" comments has all four non-neutral buckets defined).
export const __test = { MESSAGES, COLLECTIVE_OVERRIDES, ownerPrefix };
